spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/greeting
              port: 8081
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /api/greeting
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
